import { safeParseJson } from "./orchestrator.js";

export const judgeAgent = {
  name: "Judge Agent",
  sub: "Campaign Critic & Strategist",
  description: "Examines final campaign strategy, creatives, feasibility, and compliance to identify gaps, pros/cons, and analytics insights.",
  tools: ["campaign_critic_evaluator"],
  dataRequired: [],

  async run(compositeContextJson, ai, companyName = "Bath & Body Works") {
    const context = safeParseJson(compositeContextJson, { error: "Failed to parse composite campaign context." });

    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash-lite",
        contents: `You are the ${companyName} Judge Agent (Campaign Critic & Strategist). Review all of the outputs generated by preceding agents for this marketing campaign.
        
        Cumulative Campaign Outputs & Logs:
        ${JSON.stringify(context, null, 2)}
        
        Perform a thorough critical analysis and return a beautiful, clean semantic HTML report. Use premium layout cards, margins, borders, and color accents (like bg-indigo-50/40, bg-amber-50/30, bg-slate-50/50, rounded-xl, border, shadow-sm, p-4, mb-4, spacing elements) for maximum readability.
        
        Structure your report to contain these sections:
        
        1. **EXECUTIVE JUDGEMENT SUMMARY**:
           Wrap in a card with a light background. Present a high-level strategic verdict on campaign readiness.
           
         2. **STRATEGIC GAPS & ALIGNMENT ISSUES**:
            Identify if any agent outputs or creative details fail to align with the core target audience, budgets, or flight timelines.
            
         3. **PROS & CONS AUDIT**:
            Use clear split columns or bullet points. Wrap in border layouts. Use green/emerald highlights for pros and red/rose highlights for cons.
            
         4. **ACTIONABLE STRATEGY & ANALYTICS IMPROVEMENTS**:
            Specific recommendations on subject lines, CTAs, layout themes, and conversion boosters.
            
         5. **HYBRID MACHINE LEARNING & RETRAINING STRATEGIES**:
            Provide explicit guidelines on how to optimize this flow. Contrast Gemini's semantic capabilities with traditional ML models. Detail what data would be best sent into a traditional tabular ML model (e.g. BigQuery ML, XGBoost) versus Gemini processing. Specify that:
            - **Traditional ML Data**: Raw numeric shopper variables (loyalty levels, past purchase frequency, redemption rates, target margin indices, user engagement scores).
            - **Gemini Semantic Processing**: Unstructured brand tone guidelines, theme compliance checks, copy hooks, and visual context generation.

        Formatting Rules:
        - Return ONLY clean, semantic HTML inside a wrapping <div>. Do NOT return markdown or wrap the response in markdown code blocks (\`\`\`html).
        - Use <h2> for main section headers (e.g. <h2 class="text-xs font-mono font-bold uppercase tracking-wider text-indigo-700 mb-2 border-b pb-1">EXECUTIVE JUDGEMENT SUMMARY</h2>).
        - Use <h3> for sub-headings.
        - Use <p class="text-xs text-slate-600 leading-relaxed mb-3"> for paragraphs.
        - Use <ul> and <li> for list points.
        - Ensure all containers have margins (e.g. mb-6, space-y-4) to prevent text crowding.`
      });

      return response.text || "No judgement report generated.";
    } catch (err) {
      console.error("[Judge Agent Error]:", err);
      return `Judge Agent failure: ${err.message || err}`;
    }
  }
};
